apiVersion: v1
kind: Secret
metadata:
  name: google-oauth-credentials
type: Opaque
data:
  client_id: NDkwOTg2OTQ3NDU5LTNrZjI1M29zNXE0MGF1c3NxNGVzOGRvZTk0ZXMyamd xLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29t
  client_secret: R09DU1BYLUMxMEs3SU9kc0hoOXR1TGZ4MEVUU1JFUVBWbEg=